version: '3.8'
services:
  ewm-server:
    build: main-service
    image: ewm-service_image
    container_name: ewm-service
    depends_on:
      - ewm-db
      - ewm-stats-server
    ports:
      - "8012:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - STATS-SERVER_URL=http://ewm-stats-server:9090

  ewm-db:
    image: postgres:15-alpine
    container_name: ewm-db-postgress
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-stats-server:
    build: stats/stats-service
    image: ewm-stats-service_image
    container_name: ewm-stats-service
    depends_on:
      - ewm-stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  ewm-stats-db:
    image: postgres:15-alpine
    container_name: ewm-stats-db-postgress
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
